#!/bin/bash



if [ ! -e /usr/local/bin/reboot_otomatis ]; then
echo '#!/bin/bash' > /usr/local/bin/reboot_otomatis 
echo 'tanggal=$(date +"%m-%d-%Y")' >> /usr/local/bin/reboot_otomatis 
echo 'waktu=$(date +"%T")' >> /usr/local/bin/reboot_otomatis 
echo 'echo "Server telah berhasil direboot pada tanggal $tanggal pukul $waktu." >> /root/log-reboot.txt' >> /usr/local/bin/reboot_otomatis 
echo '/sbin/shutdown -r now' >> /usr/local/bin/reboot_otomatis 
chmod +x /usr/local/bin/reboot_otomatis
fi
lolcat -F 0.3 -S 0 /usr/bin/bannermenu
echo "-------------------------------------------" | lolcat
echo "Menu Sistem Reboot Otomatis" | lolcat
echo "-------------------------------------------" | lolcat
echo "1.  Set Auto-Reboot 1 jam sekali" | lolcat
echo "2.  Set Auto-Reboot 6 jam sekali" | lolcat
echo "3.  Set Auto-Reboot 12 jam sekali" | lolcat
echo "4.  Set Auto-Reboot 1 hari sekali" | lolcat
echo "5.  Set Auto-Reboot 1 minggu sekali" | lolcat
echo "6.  Set Auto-Reboot 1 bulan sekali" | lolcat
echo "7.  Matikan Auto-Reboot" | lolcat
echo "8.  Lihat log reboot" | lolcat
echo "9.  Hapus log reboot" | lolcat
echo "-------------------------------------------" | lolcat
read -p "Tulis Pilihan Anda (angka): " x

if test $x -eq 1; then
echo "10 * * * * root /usr/local/bin/reboot_otomatis" > /etc/cron.d/reboot_otomatis
echo "Auto-Reboot telah berhasil diset 1 jam sekali." | lolcat
elif test $x -eq 2; then
echo "10 */6 * * * root /usr/local/bin/reboot_otomatis" > /etc/cron.d/reboot_otomatis
echo "Auto-Reboot telah berhasil diset 6 jam sekali." | lolcat
elif test $x -eq 3; then
echo "10 */12 * * * root /usr/local/bin/reboot_otomatis" > /etc/cron.d/reboot_otomatis
echo "Auto-Reboot telah berhasil diset 12 jam sekali." | lolcat
elif test $x -eq 4; then
echo "10 0 * * * root /usr/local/bin/reboot_otomatis" > /etc/cron.d/reboot_otomatis
echo "Auto-Reboot telah berhasil diset 1 hari sekali." | lolcat
elif test $x -eq 5; then
echo "10 0 */7 * * root /usr/local/bin/reboot_otomatis" > /etc/cron.d/reboot_otomatis
echo "Auto-Reboot telah berhasil diset 1 minggu sekali." | lolcat
elif test $x -eq 6; then
echo "10 0 1 * * root /usr/local/bin/reboot_otomatis" > /etc/cron.d/reboot_otomatis
echo "Auto-Reboot telah berhasil diset 1 bulan sekali." | lolcat
elif test $x -eq 7; then
rm -f /etc/cron.d/reboot_otomatis
echo "Auto-Reboot telah berhasil dimatikan." | lolcat
elif test $x -eq 8; then
if [ ! -e /root/log-reboot.txt ]; then
	echo "Belum ada aktivitas reboot yang ditemukan" | lolcat
	else 
	echo 'LOG REBOOT' | lolcat
	echo "-------" | lolcat
	cat /root/log-reboot.txt
fi
elif test $x -eq 9; then
echo "" > /root/log-reboot.txt
echo "Log Auto Reboot berhasil dihapus!" | lolcat
else
echo "Pilihan Tidak Terdapat Di Menu." | lolcat
exit
fi